# Generated by Django 6.0.6 on 2026-06-23 09:57

import core.images.mixins
import core.images.paths
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('image', models.ImageField(upload_to=core.images.paths.original_upload_path)),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to='')),
                ('medium', models.ImageField(blank=True, editable=False, null=True, upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('product',), name='unique_main_image_per_product')],
                'unique_together': {('product', 'order')},
            },
            bases=(core.images.mixins.ImageOptimizationsMixin, models.Model),
        ),
    ]
