# Generated by Django 6.0.6 on 2026-06-25 08:34

import core.images.paths
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.images.paths.original_upload_path),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('PENDING', 'Chờ xử lý'), ('CONFIRMED', 'Đã xác nhận'), ('PACKED', 'Đã đóng gói'), ('SHIPPING', 'Đang giao hàng'), ('DELIVERED', 'Đã giao'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20)),
                ('complete', models.BooleanField(default=False)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('province_code', models.CharField(blank=True, max_length=10)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('district_code', models.CharField(blank=True, max_length=10)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('ward_code', models.CharField(blank=True, max_length=10)),
                ('hamlet', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True)),
                ('full_address', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('BANK', 'Chuyển khoản ngân hàng'), ('MOMO', 'Ví MoMo'), ('ZALOPAY', 'ZaloPay')], default='COD', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Chưa thanh toán'), ('AWAITING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('FAILED', 'Thanh toán thất bại'), ('REFUNDED', 'Đã hoàn tiền')], default='PENDING', max_length=20)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True)),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('note', models.TextField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('shipping_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('product_image', models.CharField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('BLACK', 'Black'), ('GOLD', 'Gold'), ('RED', 'Red')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='store_order_order_n_317f52_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='store_order_status_428b25_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='store_order_payment_83b142_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='store_order_created_4ba192_idx'),
        ),
    ]
